<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Bujuku" failures="5" tests="27" name="com.bookswagon.runner.TestRunner" time="631.264" errors="0" timestamp="2024-03-01T12:50:38 IST" skipped="11">
  <testcase classname="com.bookswagon.runner.TestRunner" name="runScenario" time="18.465">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at com.bookswagon.stepdefinitions.RequestBookStepDefinitions.verify_the_results(RequestBookStepDefinitions.java:77)
at ✽.verify the results(file:///C:/RLL/RLL-Group-5-BooksWagon/src/test/resources/Features/RequestBook.feature:27)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="com.bookswagon.runner.TestRunner" name="runScenario" time="17.673">
    <skipped/>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="com.bookswagon.runner.TestRunner" name="runScenario" time="55.167">
    <skipped/>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="com.bookswagon.runner.TestRunner" name="runScenario" time="25.911"/>
  <system-out/>
  <testcase classname="com.bookswagon.runner.TestRunner" name="runScenario" time="14.253"/>
  <system-out/>
  <testcase classname="com.bookswagon.runner.TestRunner" name="runScenario" time="8.997">
    <skipped/>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="com.bookswagon.runner.TestRunner" name="runScenario" time="52.418">
    <skipped/>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="com.bookswagon.runner.TestRunner" name="runScenario" time="43.685"/>
  <system-out/>
  <testcase classname="com.bookswagon.runner.TestRunner" name="runScenario" time="19.219">
    <failure message="expected [Please enter correct password.] but found [Please enter correct Passwor]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Please enter correct password.] but found [Please enter correct Passwor]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at com.bookswagon.pages.LoginPage.getWrongPasswordErrorMessage(LoginPage.java:64)
at com.bookswagon.stepdefinitions.LoginStepDefinitions.the_user_should_see_an_error_message_for_wrong_password_wrong_username(LoginStepDefinitions.java:136)
at ✽.the user should see an error message for wrong password/wrong username(file:///C:/RLL/RLL-Group-5-BooksWagon/src/test/resources/Features/Login.feature:17)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="com.bookswagon.runner.TestRunner" name="runScenario" time="17.155">
    <skipped/>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="com.bookswagon.runner.TestRunner" name="runScenario" time="8.419"/>
  <system-out/>
  <testcase classname="com.bookswagon.runner.TestRunner" name="runScenario" time="17.149">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at com.bookswagon.stepdefinitions.RequestBookStepDefinitions.verify_the_results(RequestBookStepDefinitions.java:77)
at ✽.verify the results(file:///C:/RLL/RLL-Group-5-BooksWagon/src/test/resources/Features/RequestBook.feature:27)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="com.bookswagon.runner.TestRunner" name="runScenario" time="14.068"/>
  <system-out/>
  <testcase classname="com.bookswagon.runner.TestRunner" name="runScenario" time="16.257">
    <skipped/>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="com.bookswagon.runner.TestRunner" name="runScenario" time="33.031"/>
  <system-out/>
  <testcase classname="com.bookswagon.runner.TestRunner" name="runScenario" time="17.223">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at com.bookswagon.stepdefinitions.RequestBookStepDefinitions.verify_the_results(RequestBookStepDefinitions.java:77)
at ✽.verify the results(file:///C:/RLL/RLL-Group-5-BooksWagon/src/test/resources/Features/RequestBook.feature:27)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="com.bookswagon.runner.TestRunner" name="runScenario" time="16.087">
    <skipped/>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="com.bookswagon.runner.TestRunner" name="runScenario" time="16.825"/>
  <system-out/>
  <testcase classname="com.bookswagon.runner.TestRunner" name="runScenario" time="22.280"/>
  <system-out/>
  <testcase classname="com.bookswagon.runner.TestRunner" name="runScenario" time="9.676">
    <skipped/>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="com.bookswagon.runner.TestRunner" name="runScenario" time="45.910"/>
  <system-out/>
  <testcase classname="com.bookswagon.runner.TestRunner" name="runScenario" time="18.771">
    <skipped/>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="com.bookswagon.runner.TestRunner" name="runScenario" time="16.354">
    <skipped/>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="com.bookswagon.runner.TestRunner" name="runScenario" time="52.565">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at com.bookswagon.stepdefinitions.PersonalSettingStepdefinition.user_can_not_update_the_details(PersonalSettingStepdefinition.java:111)
at ✽.User can not update the details(file:///C:/RLL/RLL-Group-5-BooksWagon/src/test/resources/Features/PersonalSettings.feature:24)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="com.bookswagon.runner.TestRunner" name="runScenario" time="15.961"/>
  <system-out/>
  <testcase classname="com.bookswagon.runner.TestRunner" name="runScenario" time="16.948">
    <skipped/>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="com.bookswagon.runner.TestRunner" name="runScenario" time="20.797"/>
  <system-out/>
</testsuite> <!-- com.bookswagon.runner.TestRunner -->
